name: Deploy our applications using CI/CD
on:
  push:
    branches: [origin]
jobs:
  buildanddeploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build a Image CI
      run: docker build -t mywebimage .
    - name: Deploy a Image to Container CD
      run: docker run -itd --name mywebapp -p 8008:80 mywebimage
