name: Deploy our applications using CI/CD
on:
  push:
    branches: [origin]
jobs:
  buildanddeploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install SSH
      run: sudo apt-get install openssh-client -y
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build a Image CI
      run: docker build -t mywebimage .
    - name: Set the docker tag
      run: docker tag mywebimage prabhu27/cicd-pipeline:latest
    - name: Deploy to Docker image to docker hub
      run: docker push prabhu27/cicd-pipeline:latest
    - name: Deploy
      env:
        HOST: ${{secrets.HOST}}
        USERNAME: ${{secrets.USERNAME}}
        KEY: ${{secrets.KEY}}
        PORT: ${{secrets.PORT}}
        DOCKER_CON_IMAGE: ${{secrets.DOCKER_CON_IMAGE}}
       run:
            docker pull prabhu27/cicd-pipeline:latest &&
            docker rm -f $DOCKER_CON_IMAGE &&
            docker run -itd --name $DOCKER_CON_IMAGE -p 8008:80 prabhu27/cicd-pipeline:latest
